# Generated by Django 4.1.7 on 2023-03-13 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='username',
        ),
    ]
