# Generated by Django 4.1.7 on 2023-04-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_remove_vendor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool_category',
            name='value',
            field=models.IntegerField(choices=[(3, '+++'), (2, '++'), (1, '+'), (0, 'Not Supported')]),
        ),
    ]
