# Generated by Django 4.1.7 on 2023-06-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_tool_category_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='ready',
            field=models.IntegerField(default=0),
        ),
    ]
