# Generated by Django 4.1.7 on 2023-06-14 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_tool_ready'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tool_category',
            unique_together={('tool', 'category')},
        ),
    ]
