# Generated by Django 4.1.7 on 2023-06-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_alter_tool_category_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
